baseURL = "https://tryallbeautyandmassage.com"
languageCode = "en"
defaultContentLanguage = "en"
title = "Tryall Beauty and Massage Center"
theme = "KeepIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
[Params]
googleAnalytics = "G-LP672MMZMD"

disqusShortname = "yourdiscussshortname"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]

  [[menu.main]]
    name = "Hair Services"
    url = "/hair"
    weight = 1
  [[menu.main]]
    name = "Hand and Foot Care"
    url = "/handfoot"
    weight = 2
  [[menu.main]]
    name = "Waxing"
    url = "/wax"
    weight = 3
  [[menu.main]]
    name = "Healing Therapies"
    url = "/massage"
    weight = 4
  [[menu.main]]
    name = "Facial Treatments"
    url = "/facial"
    weight = 5
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 6

[params]
    since = 2023
    subtitle = "Tryall Beauty and Massage Center" 
    cdn_url = ""
    home_mode = "" # post or other
    dateFormatToUse = "" # set date format, default "2 January 2006"
    
    google_verification = ""
    bing_verification = ""
    yandex_verification = ""
    pinterest_verification = ""
    baidu_verification = ""

    avatar = "/images/Tryall-bird-blue.png" #comment it to use gravatar
    socialShare = false

    description = "" # site description
    keywords = "" # site keywords

    license= 'Released under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

# Used only for Seo schema
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[deployment]
  order = [".jpg$", ".gif$"]

  [[deployment.targets]]
    name = "aws"
    URL = "s3://tryallbeautyandmassage.com?region=us-east-1"